### ISSUE TITLE
Cannot load phonlp model

### ISSUE THREAD

**Issue by MrNquyen** [VinAIResearch/PhoNLP#10]
I have a problem when loading model using this scripts:

```
phonlp.download(save_dir='/content/phonlp')
model = phonlp.load(save_dir='/content/phonlp')
```

The error occurs: 
![image](https://github.com/user-attachments/assets/182cc753-3bc2-429a-af08-49c18515377c)

Is there anything wrong with file phonlp.pt

**Comment by thelinhbkhn2014** [comment]
I just updated the model URL. Please try again. Thanks!
