### ISSUE TITLE
Make the app look more canonical

### ISSUE THREAD

**Issue by hongquan** [VinAIResearch/PhoNLP#2]
Just looked into your code, and found that it is weird, in term of organization and usage style. Some thought:

1. In development, people have to "install" the project code itself, with `pip install -e .`. I agree that we have to install the dependencies, but install the app itself is unnecessary and weird, given that we are standing right in the code base folder.
 
    Suggestion:

    - Just tell people to do `pip install -r requirements.txt` to install dependencies, or better, use [Poetry](https://python-poetry.org/) to organize dependencies.

2. The project has some CLI tools. That is good, but the way people have to `cd phonlp/models` in order to use the CLI tools is silly.

    Suggestion:

      - Organize the project so that, people just stay at the top folder and run:

      ```sh
      python3 -m phonlp.tools train ...
      ```
       
      With this organization, you also solve the 1st issue (no need to `pip install -e .`).

3. You are modifying import path:

    https://github.com/VinAIResearch/PhoNLP/blob/efda60735a0b596c7df948fb49eeb8f835cd3734/phonlp/models/run_phonlp.py#L6-L9

    With a proper organization, you don't have to do this. It is ugly when having normal code before `import` statements.

4. Code doesn't follow standard Python coding style (PEP-8).

5. Hard-code absolute folder path.
https://github.com/VinAIResearch/PhoNLP/blob/efda60735a0b596c7df948fb49eeb8f835cd3734/phonlp/models/run_phonlp.py#L28-L29

    It won't run on other people machine, because "/home/ubuntu/linhnt140/" doesn't exist there.

    Suggestion:
    - Use `~/` or `~/Documents`, it always points to user's home folder, no matter what his/her username is.

6. Command options don't follow common style. Look at this usage:

    ```sh
    python3 run_phonlp.py --mode train --save_dir ./phonlp_tmp --pretrained_lm "vinai/phobert-base"
    ```
    The popular style for CLI on Linux is GNU style, by which, the above command should be:

    ```sh
    python3 run_phonlp.py --mode train --save-dir ./phonlp_tmp --pretrained-lm "vinai/phobert-base"
    ```
    Or, combined with suggestion at 2nd issue, it should be:

    ```sh
    python3 -m phonlp.tools train --save-dir ./phonlp_tmp --pretrained-lm "vinai/phobert-base"
    ```

**Comment by datquocnguyen** [comment]
Thanks for your comment's great details. 
We will take into account your comment in the future development of the toolkit!
