### ISSUE TITLE
What if I want to train NER task only?

### ISSUE THREAD

**Issue by icyda17** [VinAIResearch/PhoNLP#4]
Hello, thanks for publishing the code. I have a question, plz help me clarify this.
What should I change the code if I only want to train NER task not the others?

**Comment by thelinhbkhn2014** [comment]
Because PhoNLP uses soft POS embedding for NER and Dependency parsing task, I think you cannot use this code for only NER task. If you only want to train NER task, you should train single NER task based on PhoBERT. I can send you the code for single NER task if you need it.

**Comment by natuhvnh** [comment]
Hi @thelinhbkhn2014, i want to train PhoBERT with NER task. Could you send me sample code to do it?

**Comment by thelinhbkhn2014** [comment]
Ok, please let me know your email. I will send my code to you.

**Comment by natuhvnh** [comment]
@thelinhbkhn2014 My email is natuhvnh@gmail.com. Thank you for sharing!

**Comment by sentry0501** [comment]
@thelinhbkhn2014  hi can u send me the code please? I'm working on Vietnamese NER using PhoBERT for my thesis... and i'm from hust too. My email is [buiphoben050199@gmail.com](mailto:buiphoben050199@gmail.com). Thank u!

**Comment by lehoangh** [comment]
@thelinhbkhn2014 Hi Linh, can you send me your code about NER using phobert? My email is hien.trannguyenle@gmail.com. Thank you very much

**Comment by huyhoang240101** [comment]
Hi, I'm trying to train a NER model in Vietnamese. Can you send me your code. My email is [huyhoang240101@gmail.com](url).
Thank you so much.

**Comment by chuan298** [comment]
@thelinhbkhn2014  Hi, I'm working about sequence labeling task. Can you send me your code about NER using phobert? My email is chuvanan29081998@gmail.com
Thank you!

**Comment by Huyne459** [comment]
Hi, I'm trying to train NER model for Vietnamese only. Can you send me the code and a document about the NER using phoBERT please. My email is vutuanhuyvth@gmail.com

Thank you so much!

**Comment by Davido111200** [comment]
@thelinhbkhn2014 I'm trying to train NER for the COVID-19 dataset. Can you send me your NER code using phobert? I would really appreciate it. My email is [davido111200@gmail.com](mailto:davido111200@gmail.com)
Thank you very much!

**Comment by cugrjt** [comment]
@thelinhbkhn2014 I'm trying to train NER for a geological dataset. Can you send me your NER code using phobert? I would really appreciate it. My email is renjiangtao@cug.edu.cn
Thank you very much!

**Comment by shed-e** [comment]
> Ok, please let me know your email. I will send my code to you.

Hello, I am trying to reproduce the NER task, Can you send me your NER code using PhoBERT? My email is shed-e@qq.com
Thank you very much!
