### ISSUE TITLE
Asking for POS/NER dataset

### ISSUE THREAD

**Issue by demdecuong** [VinAIResearch/PhoNLP#5]
Thanks for your great Vietnamese NLP toolkits .

I want to get the VLSP 2013 POS tagging dataset and the VLSP 2016 NER dataset . 
How can I get these datasets since the official website does not provide any link to download.

i am looking forward to hearing from you.

**Comment by datquocnguyen** [comment]
https://vlsp.org.vn/resources
`In order to get access to VLSP datasets, please fill out the related form, sign it and send it back to us via the following email address: vlsp dot resources at gmail dot com. `
