### ISSUE TITLE
About CRFLoss

### ISSUE THREAD

**Issue by Quang-elec44** [VinAIResearch/PhoNLP#6]
Hi, I am trying to write CRFLoss from scratch and I also read many other sources aside from your code. However, it seems that you omit the <start> and <end> tags in your code while other sources do. I saw the comment TODO in your code which tells that you will change the code in the future, aren't you? If not, is there any difference between your code and others?. 
Below are some of the references, you can check them and make comparisions. I am a newbie so I hope that you will help me out. Thanks in advance. 
https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Sequence-Labeling
https://github.com/mtreviso/linear-chain-crf/tree/865bcf25fb33f73d59978426eb1c0f587e1f95f8
https://github.com/kmkurn/pytorch-crf/blob/8f3203a1f1d7984c87718bfe31853242670258db/torchcrf/__init__.py

**Comment by thelinhbkhn2014** [comment]
I reused this function from Stanza of the Stanford NLP group. This function is another CRF version appropriate with languages built based on syllables level like Vietnamese. You can check them from Stanza Github [https://github.com/stanfordnlp/stanza](url)
