### ISSUE TITLE
what is 'dob' tag in dependecy parsing task?

### ISSUE THREAD

**Issue by icyda17** [VinAIResearch/PhoNLP#7]
After running dependency parsing task, I received the following result with a tag named 'dob'.
![image](https://user-images.githubusercontent.com/73210249/178889304-dcbcd027-d1fc-4f14-96fd-352f69dea250.png)
Please help me explain the meaning of this tag as well as provide the full list of tags :)

**Comment by datquocnguyen** [comment]
See: https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/TagsetDescription.md

**Comment by datquocnguyen** [comment]
see: https://github.com/VinAIResearch/PhoNLP/blob/master/TagsetDescription.md
